# load balance to rs
# sudo apt-get install nginx
apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  selector:
    rs: rs-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80