apiVersion: v1
kind: Node
metadata:
  name: my-name-is-master
spec:
  type: Master
  capacity:
    cpuCount: 4
    memory: 8192
    maxPods: 100
  info:
    cubeVersion: v1
    kernelVersion: 5.4
    deviceName: worker-2
status:
  addresses:
    hostName: worker-2
    internalIP: 192.168.1.5