apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: nginx
spec:
  containers:
    - name: test-pod
      image: nginx
      ports:
        - hostPort: 8086
          containerPort: 80
      volumeMounts:
        - name: conf
          mountPath: /etc/nginx/nginx.conf
  volumes:
    - name: conf
      hostPath: /etc/nginx/nginx.conf