# If you're not testing load balance, use easy-test-rs.yaml
# This yaml need to install nginx and use config under ./example/html
# sudo apt-get install nginx
apiVersion: v1
kind: ReplicaSet
metadata:
  name: test-replicaset-nginx
spec:
  replicas: 2
  selector:
    use: test-rs-nginx
  template:
    metadata:
      labels:
        use: test-rs-nginx
        rs:  rs-nginx
    spec:
      containers:
      - name: test-rs-pod
        image: nginx
        volumeMounts:
          - name: conf
            mountPath: /etc/nginx/nginx.conf
          - name: page
            mountPath: /var/www/html/index.nginx-debian.html
          - name: site
            mountPath: /etc/nginx/sites-enabled/default
      volumes:
        - name: conf
          hostPath: /etc/nginx/nginx.conf
        - name: page
          hostPath: /var/www/html/nginx1.html
        - name: site
          hostPath: /etc/nginx/sites-enabled/default
