# sudo apt-get install nginx
apiVersion: v1
kind: Dns
metadata:
  name: test-dns-nginx
spec:
  host: "example.cubernetes"
  paths:
    "/test/cubernetes/nb":
        serviceUID: "f69ecec5-7fc2-467f-be47-658bc482acbd" # svc1
        servicePort: 8080 # Fill in temporarily
    "/test/cubernetes/very/nb":
        serviceUID: "297dd7a7-5a28-4e1a-9729-cdf974a60496" # svc2
        servicePort: 80 # Fill in temporarily

