# sudo apt-get install nginx
apiVersion: v1
kind: Dns
metadata:
  name: test-dns-nginx
spec:
  host: "example.cubernetes"
  paths:
    "/test/cubernetes/nb":
        serviceUID: "8dbc5d2a-7a76-41dc-aa41-12fedb03468f" # svc1
        servicePort: 8080 # Fill in temporarily
    "/test/cubernetes/very/nb":
        serviceUID: "baa35fbf-3255-4e50-8756-666f89d09187" # svc2
        servicePort: 80 # Fill in temporarily

