# sudo apt-get install nginx
apiVersion: v1
kind: Dns
metadata:
  name: test-dns-nginx-1
spec:
  host: "example.cubernetes"
  paths:
    "/test/cubernetes/nb":
        serviceUID: "698169b0-3e01-42a8-851c-da7d0a62b440" # svc1
        servicePort: 8080 # Fill in temporarily
    "/test/cubernetes/very/nb":
        serviceUID: "22526fc8-ed69-4bdb-884b-825dc16a33a6" # svc2
        servicePort: 80 # Fill in temporarily

