# If you're not testing load balance, use test-replicaset.yaml
# sudo apt-get install nginx
apiVersion: v1
kind: ReplicaSet
metadata:
  name: test-rs
spec:
  replicas: 2
  selector:
    app: tomcat-rs
  template:
    metadata:
      labels:
        app: tomcat-rs
    spec:
      containers:
        - name: test-pod-tomcat-second-stage
          image: tomcat
          volumeMounts:
            - name: conf
              mountPath: /usr/local/tomcat/webapps
      volumes:
        - name: conf
          hostPath: /usr/tomcat-test/