apiVersion: v1
kind: Pod
metadata:
  name: test-shared-volume
spec:
  containers:
    - name: test-pod-shared-writer
      image: yiyanleee/volume-test-helper:v1.4
      volumeMounts:
        - name: conf
          mountPath: /usr/test
    - name: test-pod-shared-reader
      image:  yiyanleee/volume-web:v1
      volumeMounts:
        - name: conf
          mountPath: /usr/test
  volumes:
    - name: conf
      hostPath: /usr/test