apiVersion: v1
kind: Service
metadata:
  name: multipod-svc
spec:
  selector:
    svcname: proxy
  ports:
    - name: nginx-port
      protocol: TCP
      port: 80
      targetPortName: nginx-port
    - name: tomcat-port
      protocol: TCP
      port: 8080
      targetPortName: tomcat-port