apiVersion: v1
kind: Pod
metadata:
  name: test-multipod-service-tomcat-pod
  labels:
    svcname: proxy
spec:
  containers:
    - name: test-pod-tomcat-third-stage
      image: tomcat
      ports:
        - name: tomcat-port
          containerPort: 8080
      volumeMounts:
        - name: conf
          mountPath: /usr/local/tomcat/webapps
  volumes:
    - name: conf
      hostPath: /usr/tomcat-test/