# sudo apt-get install nginx
apiVersion: v1
kind: Dns
metadata:
  name: test-dns
spec:
  host: "example.cubernetes.nb"
  paths:
    "/nb/ass":
        serviceUID: "01849f34-1908-4278-b60f-e6561bbb3683" # Fill in temporarily
        servicePort: 8080 # Fill in temporarily
    "/cjnb/okk":
        serviceUID: "8f84c213-a440-47a8-bbe4-5a43ca874359" # Fill in temporarily
        servicePort: 80 # Fill in temporarily

