# sudo apt-get install nginx
apiVersion: v1
kind: Dns
metadata:
  name: test-dns-2
spec:
  host: "example.cubernetes.nb"
  paths:
    "/nb/ass":
        serviceUID: "fd3c04ae-b2e4-4b18-9429-1d9f4bf0125c" # Fill in temporarily
        servicePort: 8080 # Fill in temporarily
    "/cjnb/okk":
        serviceUID: "27158903-416d-477c-9aff-c06ad86372c4" # Fill in temporarily
        servicePort: 80 # Fill in temporarily

